import { useEffect, useState } from 'react';
import { Building2, ClipboardCheck, Folder, ShieldCheck, Trash2, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import api from '../api/axios';
import { useAuthStore } from '../store/authStore';
import { SecureFolder } from '../types';

/** The sole application sidebar. Add global navigation here once. */
export default function Sidebar() {
  const { user } = useAuthStore();
  const [folders, setFolders] = useState<SecureFolder[]>([]);
  useEffect(() => { void api.get('/folders').then((response) => setFolders(response.data.data.folders)).catch(() => setFolders([])); }, []);
  const role = user?.orgMemberships?.[0]?.role;
  const canApprove = user?.accountType === 'ORGANIZATION' && (role === 'OWNER' || role === 'ADMIN');
  return <aside className="w-72 shrink-0 border-r border-white/10 bg-zinc-950/35 backdrop-blur-2xl p-4 hidden lg:block"><Link to="/dashboard" className="w-full py-2 px-3 rounded-md flex items-center gap-2.5 text-sm text-muted hover:text-primary hover:bg-bg transition-colors"><Folder className="w-4 h-4 text-accent" />My Drive</Link><Link to="/dashboard?view=shared" className="w-full py-2 mt-1 px-3 rounded-md flex items-center gap-2.5 text-sm text-muted hover:text-primary hover:bg-bg transition-colors"><Users className="w-4 h-4 text-accent" />Shared with me</Link><Link to="/audit" className="w-full py-2 mt-1 px-3 rounded-md flex items-center gap-2.5 text-sm text-muted hover:text-primary hover:bg-bg transition-colors"><ShieldCheck className="w-4 h-4 text-accent" />Audit</Link><Link to="/trash" className="w-full py-2 mt-1 px-3 rounded-md flex items-center gap-2.5 text-sm text-muted hover:text-primary hover:bg-bg transition-colors"><Trash2 className="w-4 h-4 text-accent" />Trash</Link>{user?.orgMemberships?.length ? <Link to="/org/members" className="w-full py-2 mt-1 px-3 rounded-md flex items-center gap-2.5 text-sm text-muted hover:text-primary hover:bg-bg transition-colors"><Users className="w-4 h-4 text-accent" />Members</Link> : null}{canApprove ? <Link to="/approvals" className="w-full py-2 mt-1 px-3 rounded-md flex items-center gap-2.5 text-sm text-muted hover:text-primary hover:bg-bg transition-colors"><ClipboardCheck className="w-4 h-4 text-accent" />Approvals</Link> : null}<div className="mt-4 pt-3 border-t border-border space-y-0.5"><p className="px-2 pb-1.5 text-xs font-semibold text-muted uppercase tracking-wider">Organizations</p><Link to="/organizations" className="w-full py-2 px-3 rounded-md flex items-center gap-2.5 text-sm text-muted hover:text-primary hover:bg-bg transition-colors"><Building2 className="w-4 h-4 text-accent" />Discover</Link><Link to="/organizations/mine" className="w-full py-2 px-3 rounded-md flex items-center gap-2.5 text-sm text-muted hover:text-primary hover:bg-bg transition-colors"><Building2 className="w-4 h-4 text-accent" />My Organizations</Link></div><div className="mt-4 pt-3 border-t border-border space-y-0.5"><p className="px-2 pb-1.5 text-xs font-semibold text-muted uppercase tracking-wider">Folders</p>{folders.map((folder) => <Link key={folder.id} to="/dashboard" className="w-full py-2 px-3 rounded-md flex items-center gap-2.5 text-sm text-muted hover:text-primary hover:bg-bg transition-colors truncate"><Folder className="w-4 h-4 text-accent shrink-0" /><span className="truncate">{folder.name}</span></Link>)}</div></aside>;
}
