import { useEffect, useMemo, useState } from 'react';
import { Activity, Loader2 } from 'lucide-react';
import api from '../api/axios';
import { useAuthStore } from '../store/authStore';
import { AuditLog } from '../types';
import AppShell from '../components/AppShell';

const actions = ['ALL', 'UPLOAD', 'DOWNLOAD', 'SHARE', 'REVOKE_SHARE', 'DELETE', 'RESTORE', 'PERMANENT_DELETE', 'AUTO_PURGE', 'LOGIN', 'SIGNUP'];
export default function Audit() {
  const { user } = useAuthStore(); const [logs, setLogs] = useState<AuditLog[]>([]); const [action, setAction] = useState('ALL'); const [scope, setScope] = useState<'mine' | 'org'>('mine'); const [loading, setLoading] = useState(true);
  const membership = user?.orgMemberships?.[0]; const canViewOrg = membership?.role === 'OWNER' || membership?.role === 'ADMIN'; const filteredActions = useMemo(() => actions, []);
  const loadLogs = async () => { setLoading(true); try { const response = await api.get('/audit', { params: { ...(action !== 'ALL' && { action }), ...(scope === 'org' && membership?.orgId && { orgId: membership.orgId }) } }); setLogs(response.data.data.logs); } finally { setLoading(false); } };
  useEffect(() => { void loadLogs(); }, [action, scope]);
  return <AppShell><div className="max-w-7xl mx-auto px-4 sm:px-6 py-5 sm:py-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between mb-5"><h1 className="text-xl font-semibold text-primary flex items-center gap-2"><Activity className="w-5 h-5 text-accent" />Audit Log</h1><div className="flex items-center gap-2.5">{canViewOrg && <select value={scope} onChange={(event) => setScope(event.target.value as 'mine' | 'org')} className="py-2 px-3 rounded-md border border-border bg-surface text-sm text-primary"><option value="mine">My activity</option><option value="org">Org activity</option></select>}<select value={action} onChange={(event) => setAction(event.target.value)} className="py-2 px-3 rounded-md border border-border bg-surface text-sm text-primary">{filteredActions.map((item) => <option key={item} value={item}>{item === 'ALL' ? 'All actions' : item}</option>)}</select></div></div><section className="glass-panel rounded-2xl overflow-hidden"><div className="hidden sm:grid sm:grid-cols-[160px_130px_1fr] gap-3 px-4 py-3 bg-bg border-b border-border text-xs font-medium text-muted uppercase tracking-wider"><span>Timestamp</span><span>Action</span><span>Details</span></div>{loading ? <div className="h-48 flex items-center justify-center text-muted text-sm gap-2"><Loader2 className="w-4 h-4 animate-spin text-accent" />Loading activity</div> : logs.length === 0 ? <div className="h-48 flex items-center justify-center text-muted text-sm">No audit events found</div> : <div className="divide-y divide-border/60">{logs.map((log) => <div key={log.id} className="grid grid-cols-1 sm:grid-cols-[160px_130px_1fr] gap-2 sm:gap-3 items-center px-4 py-3 hover:bg-bg"><span className="text-sm text-muted">{formatDate(log.createdAt)}</span><span className="inline-block px-2 py-0.5 rounded text-xs font-medium bg-accent/10 text-accent border border-accent/20 w-fit">{log.action}</span><div className="min-w-0"><p className="text-sm text-primary font-medium">{log.targetType} <span className="text-muted font-normal">|</span> {targetName(log)}</p><p className="text-xs text-muted truncate mt-0.5">{metadataSummary(log.metadata)}</p>{scope === 'org' && <p className="text-xs text-muted mt-0.5">By: {log.user?.email}</p>}</div></div>)}</div>}</section></div></AppShell>;
}
const targetName = (log: AuditLog) => String(log.metadata?.fileName || log.metadata?.folderName || log.metadata?.targetName || log.targetId);
const metadataSummary = (metadata?: Record<string, unknown> | null) => metadata ? Object.entries(metadata).map(([key, value]) => `${key}: ${String(value)}`).join(' | ') : '';
const formatDate = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
