import { useEffect, useState } from 'react';
import { Building2, Check, Loader2, X } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import api from '../api/axios';
import AppShell from '../components/AppShell';

type Request = { id: string; requestedAt: string; user: { id: string; name: string; email: string } };

export default function JoinRequests() {
  const { orgId = '' } = useParams(); const [items, setItems] = useState<Request[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState('');
  const load = async () => { setLoading(true); try { const r = await api.get(`/orgs/${orgId}/join-requests`); setItems(r.data.data.requests); } catch { setError('You do not have permission to review join requests for this organization.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [orgId]);
  const decide = async (item: Request, decision: 'approve' | 'reject') => { setBusy(item.id); try { await api.post(`/orgs/${orgId}/join-requests/${item.id}/${decision}`); setItems((all) => all.filter((entry) => entry.id !== item.id)); } catch { setError(`Could not ${decision} this request.`); } finally { setBusy(null); } };
  return <AppShell><div className="max-w-5xl mx-auto px-4 sm:px-6 py-6 sm:py-8"><div className="flex justify-between gap-4 mb-6"><div><div className="flex gap-2 items-center text-accent"><Building2 className="w-5 h-5" /><span className="text-sm font-medium">Organization membership</span></div><h1 className="mt-1 text-2xl font-semibold text-primary">Join Requests</h1><p className="mt-1 text-sm text-muted">Approve members for this organization independently of the existing file approval queue.</p></div><Link to={`/organizations/${orgId}/drive`} className="text-sm text-accent hover:text-primary">Organization drive</Link></div><section className="glass-panel rounded-2xl overflow-hidden">{loading ? <div className="h-48 flex items-center justify-center text-muted"><Loader2 className="w-5 h-5 animate-spin" /></div> : error ? <div className="p-5 text-sm text-danger">{error}</div> : items.length === 0 ? <div className="h-48 flex flex-col items-center justify-center text-center"><Building2 className="w-10 h-10 text-accent mb-3" /><p className="font-medium text-primary">No pending join requests</p><p className="mt-1 text-sm text-muted">The membership queue is clear.</p></div> : <div className="divide-y divide-border/60">{items.map((item) => <div key={item.id} className="p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><p className="text-sm font-medium text-primary">{item.user.name}</p><p className="text-xs text-muted mt-1">{item.user.email} · Requested {new Intl.DateTimeFormat(undefined, { dateStyle: 'medium' }).format(new Date(item.requestedAt))}</p></div><div className="flex gap-2"><button disabled={busy === item.id} onClick={() => void decide(item, 'approve')} className="min-h-10 px-3 rounded-lg bg-success/15 text-success border border-success/25 text-sm font-medium flex gap-1.5 items-center disabled:opacity-60"><Check className="w-4 h-4" />Approve</button><button disabled={busy === item.id} onClick={() => void decide(item, 'reject')} className="min-h-10 px-3 rounded-lg bg-danger/15 text-danger border border-danger/25 text-sm font-medium flex gap-1.5 items-center disabled:opacity-60"><X className="w-4 h-4" />Reject</button></div></div>)}</div>}</section></div></AppShell>;
}
