import { useEffect, useState } from 'react';
import { Building2, Loader2, Search, Send } from 'lucide-react';
import api from '../api/axios';
import AppShell from '../components/AppShell';

type Org = { id: string; name: string };

export default function Organizations() {
  const [query, setQuery] = useState(''); const [results, setResults] = useState<Org[]>([]); const [searching, setSearching] = useState(false); const [busyId, setBusyId] = useState<string | null>(null); const [message, setMessage] = useState('');
  useEffect(() => { const term = query.trim(); if (!term) { setResults([]); return; } const timer = window.setTimeout(async () => { setSearching(true); try { const response = await api.get('/orgs/search', { params: { q: term } }); setResults(response.data.data.orgs); } finally { setSearching(false); } }, 300); return () => window.clearTimeout(timer); }, [query]);
  const requestJoin = async (org: Org) => { setBusyId(org.id); try { await api.post(`/orgs/${org.id}/join-request`); setResults((items) => items.filter((item) => item.id !== org.id)); setMessage(`Join request sent to ${org.name}`); } catch { setMessage('Unable to send the join request. Please try again.'); } finally { setBusyId(null); } };
  return <AppShell><div className="max-w-3xl mx-auto px-4 sm:px-6 py-6 sm:py-8"><div className="mb-7"><div className="flex gap-2 items-center text-accent"><Building2 className="w-5 h-5" /><span className="text-sm font-medium">Organizations</span></div><h1 className="mt-1 text-2xl font-semibold text-primary">Discover organizations</h1><p className="mt-1 text-sm text-muted">Search for an organization and request to join it.</p></div><section className="glass-panel rounded-2xl overflow-hidden"><div className="p-5 border-b border-border"><div className="relative"><Search className="absolute left-3 top-3 w-4 h-4 text-muted" /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search organizations" className="h-10 w-full pl-9 pr-3 rounded-lg bg-bg border border-border text-sm text-primary outline-none focus:border-accent" /></div></div><div className="divide-y divide-border/60 min-h-36">{searching ? <div className="p-6 flex justify-center text-muted"><Loader2 className="w-4 h-4 animate-spin" /></div> : query.trim() && results.length === 0 ? <p className="p-6 text-sm text-muted text-center">No organizations available for this search.</p> : results.map((org) => <div key={org.id} className="p-4 flex items-center gap-3 justify-between"><div className="min-w-0"><p className="text-sm font-medium text-primary truncate">{org.name}</p><p className="text-xs text-muted mt-1">Request access to this organization</p></div><button disabled={busyId === org.id} onClick={() => void requestJoin(org)} className="min-h-10 px-3 rounded-lg bg-accent text-bg text-sm font-medium flex items-center gap-1.5 disabled:opacity-60">{busyId === org.id ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}Request to Join</button></div>)}</div></section>{message && <div className="fixed right-5 bottom-5 rounded-xl px-4 py-3 text-sm font-medium bg-success/15 text-success border border-success/30">{message}</div>}</div></AppShell>;
}
