import { ChangeEvent, useEffect, useRef, useState } from 'react';
import { Building2, Download, FileText, Loader2, Upload } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import api from '../api/axios';
import AppShell from '../components/AppShell';
import { SecureFile } from '../types';

type DriveData = { org: { id: string; name: string }; membership: { role: string }; files: SecureFile[] };
export default function OrgDrive() {
  const { orgId = '' } = useParams(); const input = useRef<HTMLInputElement>(null); const [data, setData] = useState<DriveData | null>(null); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); const [message, setMessage] = useState('');
  const load = async () => { setLoading(true); try { const response = await api.get(`/orgs/${orgId}/drive`); setData(response.data.data); } catch { setMessage('Unable to load this organization drive.'); } finally { setLoading(false); } }; useEffect(() => { void load(); }, [orgId]);
  const upload = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; const form = new FormData(); form.append('file', file); form.append('targetOrgId', orgId); setUploading(true); try { const response = await api.post('/files/upload', form); setMessage(response.data.data.file.status === 'PENDING' ? 'Uploaded — awaiting organization approval.' : 'Uploaded to organization drive.'); await load(); } catch { setMessage('Upload failed.'); } finally { setUploading(false); } };
  const download = async (file: SecureFile) => { try { const response = await api.get(`/files/${file.id}/download`, { responseType: 'blob' }); const url = URL.createObjectURL(response.data); const link = document.createElement('a'); link.href = url; link.download = file.originalName; link.click(); URL.revokeObjectURL(url); } catch { setMessage('Download failed.'); } };
  const isAdmin = data?.membership.role === 'OWNER' || data?.membership.role === 'ADMIN';
  return <AppShell><div className="max-w-6xl mx-auto px-4 sm:px-6 py-6 sm:py-8"><div className="flex items-start justify-between gap-4 mb-6"><div><div className="flex gap-2 items-center text-accent"><Building2 className="w-5 h-5" /><span className="text-sm font-medium">Organization Drive</span></div><h1 className="mt-1 text-2xl font-semibold text-primary">{data?.org.name || 'Organization drive'}</h1><p className="mt-1 text-sm text-muted">Separate from your personal My Drive. Member uploads require approval.</p></div><div className="flex gap-3 items-center">{isAdmin && <Link to={`/organizations/${orgId}/join-requests`} className="text-sm text-accent hover:text-primary">Join Requests</Link>}<button onClick={() => input.current?.click()} disabled={uploading} className="min-h-10 px-3 rounded-lg bg-accent text-bg text-sm font-medium flex gap-2 items-center disabled:opacity-60">{uploading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Upload className="w-4 h-4" />}Upload</button><input ref={input} type="file" className="hidden" onChange={upload} /></div></div><section className="glass-panel rounded-2xl overflow-hidden">{loading ? <div className="h-52 flex justify-center items-center text-muted"><Loader2 className="w-5 h-5 animate-spin" /></div> : !data?.files.length ? <div className="h-52 flex flex-col justify-center items-center text-center"><FileText className="w-10 h-10 text-accent mb-3" /><p className="font-medium text-primary">No organization files yet</p><p className="mt-1 text-sm text-muted">Upload a file to this organization’s approval queue.</p></div> : <div className="divide-y divide-border/60">{data.files.map((file) => <div key={file.id} className="grid grid-cols-1 sm:grid-cols-[1fr_120px_auto] gap-3 items-center p-4 hover:bg-bg"><div className="min-w-0 flex gap-3 items-center"><FileText className="w-5 h-5 text-muted shrink-0" /><div className="min-w-0"><p className="text-sm font-medium text-primary truncate">{file.originalName}</p><p className="text-xs text-muted">Version {file.currentVersion}{file.status !== 'APPROVED' ? ` · ${file.status === 'PENDING' ? 'Pending approval' : 'Rejected'}` : ''}</p></div></div><span className="text-sm text-muted">{formatSize(file.size)}</span><button onClick={() => void download(file)} className="min-h-10 px-3 rounded-lg border border-border text-sm text-primary flex gap-1.5 items-center"><Download className="w-4 h-4" />Download</button></div>)}</div>}</section>{message && <div className="fixed right-5 bottom-5 rounded-xl px-4 py-3 text-sm font-medium bg-success/15 text-success border border-success/30">{message}</div>}</div></AppShell>;
}
const formatSize = (bytes: number) => bytes < 1024 ? `${bytes} B` : `${(bytes / 1024 / 1024).toFixed(1)} MB`;
