import { useEffect, useMemo, useState } from 'react';
import { FileArchive, FileImage, FileText, Folder, Loader2, RotateCcw, Trash2 } from 'lucide-react';
import api from '../api/axios';
import { TrashItem } from '../types';
import AppShell from '../components/AppShell';

export default function Trash() {
  const [items, setItems] = useState<TrashItem[]>([]); const [loading, setLoading] = useState(true); const [busyId, setBusyId] = useState<string | null>(null); const totalSize = useMemo(() => items.reduce((total, item) => total + (item.type === 'file' ? item.size : 0), 0), [items]);
  const load = async () => { setLoading(true); try { const response = await api.get('/trash'); setItems(response.data.data.items); } finally { setLoading(false); } }; useEffect(() => { void load(); }, []);
  const restore = async (item: TrashItem) => { setBusyId(item.id); try { await api.post(`/trash/${item.type}/${item.id}/restore`); await load(); } finally { setBusyId(null); } };
  const remove = async (item: TrashItem) => { if (!window.confirm(`Delete "${item.name}" forever? This cannot be undone.`)) return; setBusyId(item.id); try { await api.delete(`/trash/${item.type}/${item.id}`); await load(); } finally { setBusyId(null); } };
  const empty = async () => { if (!items.length || !window.confirm(`Delete all ${items.length} item${items.length === 1 ? '' : 's'} forever? This cannot be undone.`)) return; setBusyId('empty'); try { await api.delete('/trash/empty'); setItems([]); } finally { setBusyId(null); } };
  return <AppShell><div className="max-w-7xl mx-auto px-4 sm:px-6 py-5 sm:py-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between mb-5"><div><h1 className="text-xl font-semibold text-primary flex items-center gap-2"><Trash2 className="w-5 h-5 text-accent" />Trash</h1><p className="mt-1 text-sm text-muted">Items in Trash are automatically deleted after 30 days</p></div><button onClick={empty} disabled={!items.length || busyId === 'empty'} className="py-2 px-4 rounded-md bg-danger text-white text-sm font-medium flex items-center gap-2 disabled:opacity-50"><Trash2 className="w-4 h-4" />{busyId === 'empty' ? 'Emptying…' : `Empty Trash${items.length ? ` (${formatSize(totalSize)})` : ''}`}</button></div><section className="glass-panel rounded-2xl overflow-hidden"><div className="hidden sm:grid sm:grid-cols-[1fr_110px_180px_200px] gap-3 px-4 py-3 bg-bg border-b border-border text-xs font-medium text-muted uppercase tracking-wider"><span>Name</span><span>Size</span><span>Deleted</span><span className="text-right">Actions</span></div>{loading ? <div className="h-48 flex items-center justify-center gap-2 text-sm text-muted"><Loader2 className="w-4 h-4 animate-spin text-accent" />Loading trash</div> : items.length === 0 ? <div className="h-56 flex flex-col items-center justify-center text-muted"><Trash2 className="w-10 h-10 mb-3 text-accent/60" /><p className="text-sm font-medium text-primary">Trash is empty</p></div> : <div className="divide-y divide-border/60">{items.map((item) => <Row key={`${item.type}-${item.id}`} item={item} busy={busyId === item.id} restore={() => restore(item)} remove={() => remove(item)} />)}</div>}</section></div></AppShell>;
}
const Row = ({ item, busy, restore, remove }: { item: TrashItem; busy: boolean; restore: () => void; remove: () => void }) => { const Icon = item.type === 'folder' ? Folder : item.mimeType?.startsWith('image/') ? FileImage : item.mimeType?.includes('zip') ? FileArchive : FileText; return <div className="grid grid-cols-1 sm:grid-cols-[1fr_110px_180px_200px] gap-3 items-center px-4 py-4 hover:bg-bg"><div className="min-w-0 flex items-center gap-3"><Icon className="w-5 h-5 shrink-0 text-accent" /><p className="text-sm font-medium text-primary truncate">{item.name}</p></div><span className="text-sm text-muted">{item.type === 'file' ? formatSize(item.size) : '—'}</span><span className="text-sm text-muted">{formatDate(item.deletedAt)}</span><div className="justify-self-start sm:justify-self-end flex gap-2"><button disabled={busy} onClick={restore} className="min-h-11 py-1.5 px-2.5 rounded-md border border-border text-xs font-medium text-primary flex gap-1 items-center"><RotateCcw className="w-3.5 h-3.5" />Restore</button><button disabled={busy} onClick={remove} className="min-h-11 py-1.5 px-2.5 rounded-md border border-danger/40 text-xs font-medium text-danger flex gap-1 items-center"><Trash2 className="w-3.5 h-3.5" />Delete Forever</button></div></div>; };
const formatSize = (bytes: number) => bytes < 1024 ? `${bytes} B` : `${(bytes / 1024 / 1024).toFixed(1)} MB`;
const formatDate = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
